# Generated by Django 4.1 on 2022-08-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_like_dislikes_remove_like_likes_like_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislikes',
        ),
    ]
