# Generated by Django 4.1 on 2022-08-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_like_dislikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
